CREATE TABLE ticker_prices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticker_id  BIGINT,
    mark_date  TIMESTAMP WITHOUT TIME ZONE,
    mark_price DECIMAL,
    CONSTRAINT pk_ticker_prices PRIMARY KEY (id)
);

ALTER TABLE ticker_prices
    ADD CONSTRAINT FK_TICKER_PRICES_ON_TICKER FOREIGN KEY (ticker_id) REFERENCES tickers (id);