-- CREATE SCHEMA IF NOT EXISTS user_data;

CREATE TABLE user_data.users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_data.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_data.users
    ADD CONSTRAINT uc_users_username UNIQUE (username);